* See https://github.com/se38/abapFaker
********************************************************************************
* The MIT License (MIT)
*
* Copyright (c) 2018 abapFaker Contributors
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
********************************************************************************

CLASS zcl_faker_job_de_de DEFINITION
  PUBLIC
  INHERITING FROM zcl_faker_provider_job
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS constructor
      IMPORTING i_faker TYPE REF TO zcl_faker.

  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_faker_job_de_de IMPLEMENTATION.
  METHOD constructor.

    super->constructor( i_faker ).

  "Source: https://de.wikipedia.org/wiki/Liste_von_Ausbildungsberufen
    _job_titles = VALUE #(
( |Automobilkaufmann| )
( |Bankkaufmann| )
( |Buchhändler| )
( |Drogist| )
( |Immobilienkaufmann| )
( |Investmentfondskaufmann| )
( |Kaufmann für Dialogmarketing| )
( |Kaufmann im E-Commerce| )
( |Kaufmann im Einzelhandel| )
( |Kaufmann im Gesundheitswesen| )
( |Kaufmann im Groß- und Außenhandel| )
( |Kaufmann für Tourismus und Freizeit| )
( |Kaufmann für Versicherungen und Finanzen| )
( |Musikalienhändler| )
( |Pharmazeutisch-kaufmännischer Angestellter| )
( |Sport- und Fitnesskaufmann| )
( |Tankwart| )
( |Verkäufer| )
( |Medienkaufleute| )
( |Kaufmann für audiovisuelle Medien| )
( |Kaufmann für Marketingkommunikation| )
( |Medienkaufmann Digital und Print| )
( |Veranstaltungskaufmann| )
( |Kaufmännische Verwaltung| )
( |Bürokaufmann, Kaufmann für Bürokommunikation und Fachangestellter für Bürokommunikation)| )
( |Industriekaufmann| )
( |Kaufmann im Gesundheitswesen| )
( |Fachpraktiker für Bürokommunikation| )
( |Recht und Öffentliche Verwaltung| )
( |Fachangestellter für Arbeitsmarktdienstleistungen| )
( |Fachangestellter für Medien- und Informationsdienste| )
( |Justizfachangestellter| )
( |Notarfachangestellter| )
( |Patentanwaltsfachangestellter| )
( |Rechtsanwalts- und Notarfachangestellter| )
( |Rechtsanwaltsfachangestellter| )
( |Sozialversicherungsfachangestellter| )
( |Steuerfachangestellter| )
( |Verwaltungsfachangestellter| )
( |Beamtenausbildung: siehe unter Beamtenanwärter| )
( |Kaufmännische Verkehrsberufe| )
( |Fachkraft für Kurier-, Express- und Postdienstleistungen| )
( |Fachkraft für Möbel-, Küchen- und Umzugsservice| )
( |Kaufmann für Kurier-, Express- und Postdienstleistungen| )
( |Kaufmann für Spedition und Logistikdienstleistung| )
( |Kaufmann für Verkehrsservice| )
( |Kaufmann im Eisenbahn- und Straßenverkehr| )
( |Luftverkehrskaufmann| )
( |Reiseverkehrskaufmann| )
( |Schifffahrtskaufmann| )
( |Servicekaufmann im Luftverkehr| )
( |Transport und Logistik| )
( |Berufskraftfahrer| )
( |Binnenschiffer| )
( |Eisenbahner im Betriebsdienst| )
( |Ewerführer| )
( |Fachkraft für Lagerlogistik| )
( |Fachkraft für Lagerwirtschaft| )
( |Fachlagerist| )
( |Fachkraft für Kurier-, Express und Postdienstleistungen| )
( |Fachkraft im Fahrbetrieb| )
( |Hafenschiffer| )
( |Fachkraft für Hafenlogistik| )
( |Servicefahrer| )
( |Bergleute| )
( |Aufbereitungsmechaniker| )
( |Berg- und Maschinenmann| )
( |Bergbautechnologe| )
( |Metallberufe| )
( |Produktionstechnologe| )
( |Fertigungstechnik| )
( |Behälter- und Apparatebauer| )
( |Bohrwerkdreher| )
( |Büchsenmacher| )
( |Chirurgiemechaniker| )
( |Drahtwarenmacher| )
( |Drahtzieher| )
( |Federmacher| )
( |Feinpolierer| )
( |Feinwerkmechaniker| )
( |Fertigungsmechaniker| )
( |Galvaniseur| )
( |Gerätezusammensetzer| )
( |Gießereimechaniker| )
( |Graveur| )
( |Industriemechaniker| )
( |Kabeljungwerker| )
( |Maschinenzusammensetzer| )
( |Maschinen- und Anlagenführer| )
( |Metall- und Glockengießer| )
( |Metallschleifer| )
( |Metalltechniker (Österreich)| )
( |Metallverformer| )
( |Revolverdreher| )
( |Schleifer| )
( |Schneidwerkzeugmechaniker| )
( |Teilezurichter| )
( |Verfahrensmechaniker für Kunststoff- und Kautschuktechnik| )
( |Verfahrensmechaniker in der Hütten- und Halbzeugindustrie| )
( |Vorpolierer Schmuck- und Kleingeräteherstellung (Industrie)| )
( |Zerspanungsmechaniker| )
( |Installations- und Metallbautechnik| )
( |Anlagenmechaniker| )
( |Anlagenmechaniker für Sanitär-, Heizungs- und Klimatechnik| )
( |Kälteanlagenbauer| )
( |Klempner| )
( |Konstruktionsmechaniker| )
( |Metallbauer| )
( |Fahrzeugtechnik/Seefahrt| )
( |Fahrradmonteur| )
( |Fahrzeuginnenausstatter| )
( |Fahrzeuglackierer| )
( |Fluggerätmechaniker| )
( |Karosserie- und Fahrzeugbaumechaniker| )
( |Kraftfahrzeugmechatroniker| )
( |Landmaschinenmechaniker| )
( |Mechaniker für Karosserieinstandhaltungstechnik| )
( |Mechaniker für Land- und Baumaschinentechnik| )
( |Schiffsmechaniker| )
( |Zweiradmechaniker| )
( |Metallgestaltung| )
( |Edelsteinfasser| )
( |Goldschmied| )
( |Hufschmied| )
( |Metallbildner| )
( |Silberschmied| )
( |Uhrmacher| )
( |Werkgehilfe Schmuckwarenindustrie, Taschen- und Armbanduhren| )
( |Edelsteinberufe| )
( |Diamantschleifer| )
( |Edelsteingraveur| )
( |Edelsteinschleifer| )
( |Elektroberufe| )
( |Elektroanlagenmonteur| )
( |Elektroinstallateur| )
( |Elektroniker für Automatisierungstechnik| )
( |Elektroniker für Betriebstechnik| )
( |Elektroniker für Gebäude- und Infrastruktursysteme| )
( |Elektroniker für Geräte und Systeme| )
( |Elektroniker für Maschinen und Antriebstechnik| )
( |Elektroniker für luftfahrttechnische Systeme| )
( |Elektroniker| )
( |Energieelektroniker| )
( |Industrieelektriker| )
( |Informationselektroniker| )
( |Mechatroniker| )
( |Mikrotechnologe| )
( |Systemelektroniker| )
( |IT-Berufe| )
( |Fachinformatiker| )
( |Industrietechnologe| )
( |Informatikkaufmann| )
( |IT-Systemelektroniker| )
( |IT-Systemkaufmann| )
( |Mathematisch-technischer Softwareentwickler| )
( |Technischer Assistent für Informatik| )
( |Systeminformatiker| )
( |Fachinformatiker Systemintegration| )
( |Fachinformatiker Anwendungsentwicklung| )
( |Bauberufe| )
( |Baugeräteführer| )
( |Steinbearbeiter| )
( |Naturwerksteinmechaniker| )
( |Steinbildhauer| )
( |Steinmetz| )
( |Baustoffhersteller| )
( |Betonfertigteilbauer| )
( |Werksteinhersteller| )
( |Verfahrensmechaniker in der Steine- und Erdenindustrie| )
( |Tiefbau| )
( |Asphaltbauer| )
( |Brunnenbauer| )
( |Gleisbauer| )
( |Kanalbauer| )
( |Rohrleitungsbauer| )
( |Spezialtiefbauer| )
( |Straßenbauer| )
( |Straßenwärter| )
( |Tiefbaufacharbeiter| )
( |Wasserbauer| )
( |Hochbau| )
( |Backofenbauer| )
( |Beton- und Stahlbetonbauer| )
( |Fassadenmonteur| )
( |Feuerungs- und Schornsteinbauer| )
( |Gerüstbauer| )
( |Hochbaufacharbeiter| )
( |Maurer| )
( |Ausbau| )
( |Ausbaufacharbeiter| )
( |Bauwerksabdichter| )
( |Dachdecker| )
( |Estrichleger| )
( |Fliesen-, Platten- und Mosaikleger| )
( |Industrie-Isolierer| )
( |Isolierfacharbeiter| )
( |Ofen- und Luftheizungsbauer| )
( |Schiffszimmerer| )
( |Stuckateur| )
( |Trockenbaumonteur| )
( |Wärme-, Kälte- und Schallschutzisolierer| )
( |Zimmerer| )
( |Maler| )
( |Bauten- und Objektbeschichter| )
( |Bühnenmaler und -plastiker| )
( |Maler und Lackierer| )
( |Schauwerbegestalter| )
( |Schilder- und Lichtreklamehersteller| )
( |Verfahrensmechaniker für Beschichtungstechnik| )
( |Vergolder| )
( |Raumausstatter| )
( |Bodenleger| )
( |Parkettleger| )
( |Polster- und Dekorationsnäher| )
( |Polsterer| )
( |Raumausstatter| )
( |Holzberufe| )
( |Biologiemodellmacher| )
( |Bootsbauer| )
( |Bürsten- und Pinselmacher| )
( |Drechsler (Elfenbeinschnitzer)| )
( |Fachkraft für Holz- und Bautenschutzarbeiten| )
( |Flechtwerkgestalter (früher: Korbmacher)| )
( |Glaser| )
( |Holzbearbeitungsmechaniker| )
( |Holzbildhauer| )
( |Holzmechaniker| )
( |Holzspielzeugmacher| )
( |Holz- und Bautenschützer| )
( |Böttcher| )
( |Leichtflugzeugbauer| )
( |Rollladen- und Sonnenschutzmechatroniker| )
( |Schirmmacher| )
( |Spielzeughersteller| )
( |Technischer Modellbauer| )
( |Tischler| )
( |Musikinstrumentenberufe| )
( |Bogenmacher (lat.: Agittarius)| )
( |Geigenbauer| )
( |Handzuginstrumentenmacher| )
( |Holzblasinstrumentenmacher| )
( |Klavier- und Cembalobauer| )
( |Metallblasinstrumentenmacher| )
( |Orgel- und Harmoniumbauer| )
( |Zupfinstrumentenmacher| )
( |Textil- und Bekleidungsberufe| )
( |Textilberufe| )
( |Polster- und Dekorationsnäher| )
( |Gestalter für visuelles Marketing| )
( |Polsterer| )
( |Produktgestalter Textil| )
( |Produktionsmechaniker Textil| )
( |Produktprüfer Textil| )
( |Produktveredler Textil| )
( |Raumausstatter| )
( |Segelmacher| )
( |Seiler| )
( |Sticker| )
( |Stricker| )
( |Technischer Konfektionär| )
( |Textillaborant| )
( |Textilreiniger| )
( |Weber| )
( |Bekleidungsberufe| )
( |Änderungsschneider| )
( |Maßschneider| )
( |Modenäher| )
( |Modeschneider| )
( |Modist| )
( |Designer| )
( |Pelz- und Lederberufe| )
( |Fachkraft für Lederverarbeitung| )
( |Gerber| )
( |Handschuhmacher| )
( |Kürschner| )
( |Pelzveredler| )
( |Sattler| )
( |Schuhfertiger| )
( |Schuhmacher| )
( |Chemie, Physik, Biologie| )
( |Physikalisch/chemische Produktionsberufe| )
( |Produktionsfachkraft Chemie| )
( |Chemielaborant| )
( |Chemielaborjungwerker| )
( |Chemikant| )
( |Mikrotechnologe| )
( |Pharmakant| )
( |Wachszieher| )
( |Papierhersteller| )
( |Papiermacher| )
( |Laborberufe| )
( |Baustoffprüfer| )
( |Biologielaborant| )
( |Biologisch-Technischer Assistent| )
( |Chemielaborant| )
( |Chemisch-Technischer Assistent| )
( |Edelmetallprüfer| )
( |Lacklaborant| )
( |Landwirtschaftlich-Technischer Laborant| )
( |Landwirtschaftlicher Laborant| )
( |Milchwirtschaftlicher Laborant| )
( |Pharmazeutisch-technischer Assistent| )
( |Physiklaborant| )
( |Stoffprüfer (Chemie) Glas-, Keramische Industrie sowie Steine und Erden| )
( |Textillaborant| )
( |Werkstoffprüfer| )
( |Keramik- und Glasberufe| )
( |Dekorvorlagenhersteller| )
( |Feinoptiker| )
( |Figurenkeramformer| )
( |Flachglasmechaniker| )
( |Glas- und Porzellanmaler| )
( |Glasapparatebauer| )
( |Glasbläser| )
( |Glasmacher| )
( |Glasveredler| )
( |Industriekeramiker Anlagentechnik| )
( |Industriekeramiker Dekorationstechnik| )
( |Industriekeramiker Modelltechnik| )
( |Industriekeramiker Verfahrenstechnik| )
( |Keramiker| )
( |Leuchtröhrenglasbläser| )
( |Manufakturporzellanmaler| )
( |Thermometermacher| )
( |Verfahrensmechaniker Glastechnik| )
( |Verfahrensmechaniker für Brillenoptik| )
( |Medienberufe| )
( |Papierverarbeiter, Druckformenhersteller und Drucker| )
( |Buchbinder| )
( |Medientechnologe Druck| )
( |Flexograf| )
( |Mediengestalter Digital und Print| )
( |Notenstecher| )
( |Papiertechnologe| )
( |Schriftsetzer| )
( |Siebdrucker| )
( |Steindrucker| )
( |AV-Medienberufe| )
( |Fachangestellter für Medien- und Informationsdienste| )
( |Fachkraft für Veranstaltungstechnik| )
( |Film- und Videoeditor| )
( |Mediengestalter Bild und Ton| )
( |Fotograf| )
( |Fotolaborant| )
( |Fototechnischer Assistent| )
( |Filmkopienfertiger| )
( |Fotomedienfachmann| )
( |Fotomedienlaborant| )
( |Gestaltungstechnischer Assistent| )
( |Gestaltungs- und medientechnischer Assistent| )
( |Grafikdesigner| )
( |Mediengestalter Digital und Print| )
( |Gesundheit, Körperpflege, Soziales| )
( |Gesundheitsfachberufe| )
( |Altenpfleger| )
( |Altenpflegehelfer| )
( |Diätassistent| )
( |Ergotherapeut| )
( |Hebamme| )
( |Heilerziehungspfleger| )
( |Gesundheits- und Kinderkrankenpfleger| )
( |Gesundheits- und Krankenpfleger| )
( |Gesundheits- und Krankenpflegehelfer| )
( |Logopäde| )
( |Masseur und medizinischer Bademeister| )
( |Medizinisch-Technischer Assistent| )
( |Medizinischer Fachangestellter| )
( |Orthoptist| )
( |Physiotherapeut| )
( |Präparator| )
( |Podologe| )
( |Rettungsassistent bzw. Notfallsanitäter| )
( |Tiermedizinischer Fachangestellter| )
( |Zahnmedizinische Fachangestellte| )
( |Operationstechnischer Assistent| )
( |Sozialberufe| )
( |Assistenz (Behindertenhilfe)| )
( |Erzieher| )
( |Heilerziehungspfleger| )
( |Gesundheits-Handwerker| )
( |Augenoptiker| )
( |Hörgeräteakustiker| )
( |Orthopädietechnik-Mechaniker| )
( |Orthopädieschuhtechniker| )
( |Zahntechniker| )
( |Fachkraft für Zahnmedizinische Angelegenheiten| )
( |Körperpflege-Handwerker| )
( |Friseur| )
( |Kosmetiker| )
( |Masseur| )
( |Sonstige Dienstleistungsberufe| )
( |Bestattungsfachkraft| )
( |Fachangestellter für Bäderbetriebe| )
( |Maskenbildner| )
( |Servicefachkraft für Dialogmarketing| )
( |Bauhoffacharbeiter| )
( |Fachkraft für Schutz und Sicherheit| )
( |Gebäudereiniger| )
( |Schornsteinfeger| )
( |Ernährungsberufe| )
( |Brauer und Mälzer| )
( |Brenner| )
( |Bäcker| )
( |Destillateur| )
( |Fachkraft für Fruchtsafttechnik| )
( |Fachkraft für Lebensmitteltechnik| )
( |Fachkraft für Süßwarentechnik| )
( |Fachverkäufer im Lebensmittelhandwerk| )
( |Fleischer| )
( |Konditor| )
( |Molkereifachmann| )
( |Müller (Verfahrenstechnologe/technologin Mühlen- und Getreidewirtschaft)| )
( |Weinküfer| )
( |Gastgewerbe und Hauswirtschaft| )
( |Fachkraft im Gastgewerbe| )
( |Fachmann für Systemgastronomie| )
( |Hauswirtschafter| )
( |Hotelfachmann| )
( |Hotelkaufmann| )
( |Koch| )
( |Restaurantfachmann| )
( |Landwirtschaftliche Berufe| )
( |Fachkraft Agrarservice| )
( |Fischwirt| )
( |Florist| )
( |Forstwirt| )
( |Gärtner| )
( |Landwirt| )
( |Pferdewirt| )
( |Revierjäger| )
( |Tierpfleger| )
( |Tierwirt| )
( |Winzer| )
( |Umweltschutzberufe| )
( |Fachkraft für Abwassertechnik| )
( |Fachkraft für Kreislauf- und Abfallwirtschaft| )
( |Fachkraft für Rohr-, Kanal- und Industrieservice| )
( |Fachkraft für Wasserversorgungstechnik| )
( |Technische Berufe| )
( |Baustoffprüfer| )
( |Bauzeichner| )
( |Denkmaltechnischer Assistent| )
( |Fachkraft für Straßen- und Verkehrstechnik| )
( |Fachkraft für Wasserwirtschaft| )
( |Geomatiker| )
( |Technischer Produktdesigner| )
( |Technischer Zeichner| )
( |Vermessungstechniker| )
( |Verpackungsmittelmechaniker| )
( |Werkfeuerwehrmann| )
( |Werkstoffprüfer| )
    ).

  ENDMETHOD.

ENDCLASS.
